flask_7_平台/blueprints/index.py
from flask import Blueprint,render_template

bp = Blueprint("index", __name__, url_prefix="/")


@bp.route("/")
def index():
   return render_template('index.html')

flask_7_平台/blueprints/laboratory.py
from flask import Blueprint,render_template,request,flash
import DFA
from decorators import login_required


bp = Blueprint("laboratory", __name__, url_prefix="/laboratory")


@bp.route("/index", methods=['GET', 'POST'])
@login_required
# 装饰器,把public_question当作参数传入login_required
# @login_required
# 遇到public_question执行login_required(public_question)的返回值
def index():
    if request.method == 'GET':
        return render_template('laboratory.html')
    else:
          content = request.form.get('content')
          result1 = DFA.cut_deal(content)
          result2 =DFA.cuttest(content)
          # flash("分词结果为：" + content)
          flash("分词结果为："+ result1)
          flash("输出结果为：" + result2)
          return render_template('laboratory.html')










flask_7_平台/blueprints/qa.py
from flask import Blueprint, render_template, g, request, redirect, flash, url_for
from decorators import login_required
from .forms import QuestionForm, AnswerForm
from models import QuestionModel, AnswerModel
from exts import db
from sqlalchemy import or_
import DFA
bp = Blueprint("qa", __name__, url_prefix="/qa")


@bp.route("/")
def index():
    questions = QuestionModel.query.order_by(db.text('-create_time')).all()
    return render_template('qa.html', questions=questions)


@bp.route("/public_question", methods=['GET', 'POST'])
# 装饰器,把public_question当作参数传入login_required
@login_required
# 遇到public_question执行login_required(public_question)的返回值
def public_question():
    if request.method == 'GET':
        return render_template('public_question.html')
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = DFA.cuttest(form.title.data)
            content = DFA.cuttest(form.content.data)
            question = QuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect("/qa")
        else:
            flash("标题或格式错误")
            return redirect(url_for("qa.public_question"))


@bp.route("/question/<int:question_id>")
def question_detail(question_id):
    question = QuestionModel.query.get(question_id)
    return render_template("detail.html", question=question)


@bp.route("/answer/<int:question_id>", methods=['post'])
@login_required
def answer(question_id):
    form = AnswerForm(request.form)
    if form.validate():
        content = DFA.cuttest(form.content.data)
        # question_id = form.question_id.data
        answer_model = AnswerModel(content=content, author=g.user, question_id=question_id)
        db.session.add(answer_model)
        db.session.commit()
        return redirect(url_for("qa.question_detail", question_id=question_id))
    else:
        flash("表单验证失败")
        return redirect(url_for("qa.question_detail", question_id=question_id))


@bp.route('/search')
def search():
    q = request.args.get("q")
    questions = QuestionModel.query.filter(or_(QuestionModel.title.contains(q),QuestionModel.content.contains(q)))
    return render_template("qa.html",questions=questions)


flask_7_平台/blueprints/user.py
from flask import (
    Blueprint, render_template, request,
    redirect, url_for, jsonify,session,flash
)
from exts import mail, db
from flask_mail import Message
from models import EmailCaptchaModel, UserModel
import string
import random
from datetime import datetime
from .forms import RegisterForm,LoginForm
from werkzeug.security import generate_password_hash,check_password_hash

bp = Blueprint("user", __name__, url_prefix="/user")


@bp.route("/login",methods=['POST','GET'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form =LoginForm(request.form)
        if form.validate():
            email =form.email.data
            password =form.password.data
            user =UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password,password):
                session['user_id'] =user.id
                # 密码正确,返回首页
                return  redirect("/")
            else:
                # 密码不正确返回登录页面,重新登录
                flash("密码不正确")
                return redirect(url_for("user.login"))
        else:
            flash("邮箱或密码格式输入错误")
            # 表单验证错误,邮箱密码格式输入错误,返回登录页面,重新登录
            return  redirect(url_for("user.login"))



@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for('user.login'))






@bp.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            hash_password = generate_password_hash(password)

            user = UserModel(email=email, username=username, password=hash_password)

            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("user.register"))


@bp.route("/captcha", methods=['POST'])
def get_captcha():
    # GET请求邮箱
    email = request.form.get("email")
    letters_string = string.ascii_letters + string.digits
    captcha = "".join(random.sample(letters_string, 4))

    if email:
        message = Message(
            subject='邮箱测试',
            recipients=[email],
            body=f"[敏感词检测]您的注册验证是:{captcha}",
        )
        mail.send(message)
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.now()
            print(captcha)
            db.session.commit()
        else:
            captcha_model = EmailCaptchaModel(email=email, captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()
            # code:200 成功
        return jsonify({"code": 200})
    else:
        # code:400 客户端错误
        return jsonify({"code": 400, "message": "请输入邮箱"})

flask_7_平台/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/bootstrap@4.6.min.css') }}">
  <script src="jquery/jquery.3.6.min.js" type="text/javascript"></script>
  <script src="jquery/bootstrap.min.js" type="text/javascript"></script>
  <link rel="stylesheet" href="{{ url_for('static',filename='css/init.css') }}">

  {% block head %}{% endblock %}


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">检测系统</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('index.index') }}">首页 <span class="sr-only"></span></a>
        </li>
        <li class="nav-item ml-2">
          <a class="nav-link" href="{{ url_for('laboratory.index') }}">体验区</a>
        </li>

            <li class="nav-item ml-2">
              <a class="nav-link" href="{{ url_for('qa.index') }}">论坛</a>
            </li>

             <li class="nav-item ml-2">
              <a class="nav-link" href="{{ url_for('qa.public_question') }}">发布问答</a>
             </li>

{#              <li class="nav-item dropdown">#}
{#                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">#}
{#                  功能列表#}
{#                </a>#}
{#                <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#                  <a class="dropdown-item" href="#">Action</a>#}
{#                  <a class="dropdown-item" href="#">Another action</a>#}
{#                  <a class="dropdown-item" href="#">Something else here</a>#}
{#                </div>#}
{#              </li>#}
{#              <li class="nav-item">#}
{#                <a class="nav-link disabled">Disabled</a>#}
{#              </li>#}



        <li class="nav-item pl-5 ">
          <form class="form-inline my-5 my-lg-0" method="get" action="{{ url_for('qa.search') }}">
            <input  name="q" class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
          </form>
        </li>

      </ul>

      <ul class="navbar-nav mr-auto">
        {% if user %}
          <li class="nav-item ">
            <span class="nav-link">{{ user.username }}</span>
          </li>
          <li class="nav-item ml-2">
            <a class="nav-link" href="{{ url_for('user.logout') }}">注销</a>
          </li>
        {% else %}
          <li class="nav-item ">
            <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
          </li>
          <li class="nav-item ml-2">
            <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
          </li>
        {% endif %}
        {#      <li class="nav-item dropdown">#}
        {#        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">#}
        {#          功能列表#}
        {#        </a>#}
        {#        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
        {#          <a class="dropdown-item" href="#">Action</a>#}
        {#          <a class="dropdown-item" href="#">Another action</a>#}
        {#          <div class="dropdown-divider">111</div>#}
        {#          <a class="dropdown-item" href="#">Something else here</a>#}
        {#        </div>#}
        {#      </li>#}
        {#      <li class="nav-item">#}
        {#        <a class="nav-link disabled">Disabled</a>#}
        {#      </li>#}
        {#        <li class="nav-item">#}
        {#            <form class="form-inline my-2 my-lg-0">#}
        {#      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
        {#      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
        </form>
        </li>

      </ul>

    </div>


  </div>
</nav>

<div class="container">
  {% block body %}
  {% endblock %}

</div>

</body>
</html>

flask_7_平台/templates/detail.html
{% extends "base.html" %}

{% block title %}{{question.title}}{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css') }}">
{% endblock %}

{% block body %}
  <div class="row " style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-8" style="background-color: #ffffff;padding: 20px">
      <h3 class="pape-title">{{ question.title }}</h3>
      <p class="question-info">
        <span>作者:{{ question.author.username }}</span>
        <span>时间:{{ question.create_time }}</span>
      </p>
      <hr>
      <p class="question content">{{ question.content }}</p>
      <hr>

      <h4 class="comment-group-title"> 评论{{ question.answers|length }}</h4>
      <form action="{{ url_for('qa.answer',question_id=question.id) }}" method="post">
{#        <input type="hidden"name="question_id" value="{{ question_id }}">#}
        <div class="form-group">
          <input type="text" placeholder="请填写评论" name="content" class="form-control">
        </div>

        <div>
          {% for message in get_flashed_messages() %}
            <div class="text-danger">{{ message }}</div>
          {%  endfor %}
        </div>

        <div class="form-group" style="text-align: right">
          <button class="btn btn-primary">评论</button>
        </div>
      </form>
      <ul class="comment-group">
        {% for answer in question.answers %}
          <li>
          <div class="user-info">
            <img class="avatar" width="40px" height="40px" src="{{ url_for('static',filename='images/avatar.jpg') }}" alt="" >
            <span class="username">{{answer.author.username}}</span>
            <span class="creat-time">{{ answer.create_time }}</span>
          </div>
          <p class="comment-content">{{answer.content}}</p>
        </li>
        
        {% endfor %}
        
      </ul>
    </div>
    <div class="col"></div>
  </div>

{% endblock %}

flask_7_平台/templates/index.html
{% extends "base.html" %}

{% block title %}敏感词检测-首页{% endblock %}



{% block head %}

{% endblock %}


{% block body %}
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-4">文本内容安全</h1>
      <p class="lead">基于自然语言理解、深度学习等技术，有效识别违规文本内容，具备拆字识别能力；支持自定义黑白名单，可灵活调整审核策略和松紧度，更贴合当前复杂的网络环境需求</p>
      <hr class="my-4">
      <p>适用于文章内容审核、社区论坛留言等，对用户评论信息进行检测，一旦发现用户提交违规内容，进行自动审核与实时过滤</p>
      <a class="btn btn-primary btn-lg" href="{{ url_for('laboratory.index') }}" role="button">立即体验</a>
    </div>
  </div>

  <div class="container">
    <h1 class="text-center">功能介绍</h1>

  </div>
  <div class="container">
    <div class="row mt-4  ">


      <div class="col-4 clearfix ">
        <div  style="width: 18rem;">
{#          <img src="..." class="card-img-top" alt="...">#}
          <div class="card-body">
            <h5 class="card-title">智能鉴黄</h5>
            <p class="card-text">识别文本中的色情行为描述、色情资源链接、低俗交友、污秽文爱等涉黄内容</p>
{#            <a href="#" class="btn btn-primary">Go somewhere</a>#}
          </div>
        </div>
      </div>


      <div class="col-4 clearfix ">
        <div  style="width: 18rem;">
{#          <img src="..." class="card-img-top" alt="...">#}
          <div class="card-body">
            <h5 class="card-title">违禁违规</h5>
            <p class="card-text">识别暴力行为、恐怖描述、赌博、毒品、枪支弹药等违禁文字内容</p>
{#            <a href="#" class="btn btn-primary">Go somewhere</a>#}
          </div>
        </div>
      </div>


      <div class="col-4 clearfix  ">
        <div  style="width: 18rem;">
{#          <img src="..." class="card-img-top" alt="...">#}
          <div class="card-body">
            <h5 class="card-title">恶意推广</h5>
            <p class="card-text">识别带有售卖意向的软文广告、微信/QQ/联系方式等违规广告，支持包含符号、图标等变异广告</p>
{#            <a href="#" class="btn btn-primary">Go somewhere</a>#}
          </div>
        </div>
      </div>

    </div>
    <div class="row mt-4 ">


      <div class="col-4 ">
        <div  style="width: 18rem;">
{#          <img src="..." class="card-img-top" alt="...">#}
          <div class="card-body">
            <h5 class="card-title">低俗辱骂</h5>
            <p class="card-text">识别文本中的侮辱谩骂、人身攻击、消极宣泄等不良内容</p>
{#            <a href="#" class="btn btn-primary">Go somewhere</a>#}
          </div>
        </div>
      </div>


      <div class="col-4 ">
        <div  style="width: 18rem;">
{#          <img src="..." class="card-img-top" alt="...">#}
          <div class="card-body">
            <h5 class="card-title">自定义类</h5>
            <p class="card-text">支持自定义黑白名单，可灵活调整审核策略和松紧度，更贴合业务需求</p>
{#            <a href="#" class="btn btn-primary">Go somewhere</a>#}
          </div>
        </div>
      </div>

      <div class="col-4"></div>

    </div>
  </div>





{% endblock %}

flask_7_平台/templates/laboratory.html
{% extends "base.html" %}

{% block title %}敏感词检测-实验室{% endblock %}



{% block head %}

{% endblock %}


{% block body %}
  <div class="row">
    <div class="col"></div>


    <div class="col-6 text-center">
      <div class="container">
        <h1 class="text-center">功能体验区</h1>
      </div>
      <form action="{{ url_for('laboratory.index') }}" method="POST">
        <div class="form-group">
          <textarea name="content" class="form-control" rows="10" id="1">请输入内容</textarea>
        </div>
        <div class="form-group">
          {% for message in get_flashed_messages() %}
            <div class="text-danger">{{ message }}</div>
          {%  endfor %}
        </div>
        <div class="form-group" style="text-align: right">
          <button class="btn btn-primary">开始检测</button>
        </div>
      </form>
    </div>
    <div class="col"></div>
  </div>



{% endblock %}

flask_7_平台/templates/login.html
{% extends "base.html" %}

{% block title %}登录{% endblock %}



{% block head %}{% endblock %}


{% block body %}
  <div class="row">
    <div class="col-sm">

    </div>
    <div class="col-sm">

      <form action="{{ url_for("user.login") }}" method="POST">
        <div class="form-group">
          <label for="exampleInputEmail1">邮箱</label>
          <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1" >密码</label>
          <input type="password" class="form-control" name="password" id="exampleInputPassword1">
        </div>

        <div class="form-group">
          {% for message in get_flashed_messages() %}
            <div class="text-danger">{{ message }}</div>
          {%  endfor %}
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block ">立即登录</button>
        </div>

      </form>
    </div>
    <div class="col-sm">

    </div>
  </div>



{% endblock %}

flask_7_平台/templates/public_question.html
{% extends "base.html" %}

{% block title  %}发布问答{% endblock %}

{% block head %}

{% endblock %}


{% block body %}
<div class="row">
  <div class="col"></div>


  <div class="col-6 text-center">
    <h1>发布问答</h1>
    <form action="{{ url_for('qa.public_question') }}" method="POST">
      <div class="form-group">
        <input type="text" name="title" placeholder="请输入标题" class="form-control">
      </div>
      <div class="form-group">
        <textarea name="content" class="form-control"  rows="10">请输入内容</textarea>
      </div>
        <div class="form-group">
          {% for message in get_flashed_messages() %}
            <div class="text-danger">{{ message }}</div>
          {%  endfor %}
        </div>


      <div class="form-group" style="text-align: right">
        <button class="btn btn-primary">发布</button>
      </div>
    </form>

  </div>


  <div class="col"></div>

</div>



{% endblock %}

flask_7_平台/templates/qa.html
{% extends "base.html" %}

{% block title  %}聊天室{% endblock %}



{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='css/qa.css') }}">
{% endblock %}


{% block body %}
<div class="row" style="margin-top: 20px;">
  <div class="col"></div>
  <div class="col-8">
     <ul class="question-ul">
       {% for question in questions %}
          <li>
         <div class="side-question">
           <img class="side-question-avatar" src="{{ url_for('static',filename='images/avatar.jpg') }}" alt="">
         </div>
         <div class="question-main">
           <div class="question-title"><a href="{{ url_for('qa.question_detail',question_id=question.id) }}">{{ question.title }}</a></div>
           <div class="question-content">{{ question.content }}</div>
           <div class="question-detail">
             <span class="question-author">{{question.author.username}}</span>
             <span class="question-time">{{ question.create_time }}</span>
           </div>
         </div>
       </li>
       {% endfor %}
       
     </ul>
  </div>
  <div class="col"></div>
</div>

{% endblock %}

flask_7_平台/templates/register.html
{% extends "base.html" %}

{% block title %}注册{% endblock %}



{% block head %}
  <script src="{{ url_for('static',filename='jquery/jquery.3.6.min.js') }}"></script>
  <script src="{{ url_for('static',filename='js/register.js' ) }}"></script>
{% endblock %}


{% block body %}
  <div class="row mt-4">
    <div class="col-sm"></div>
    <div class="col-sm">


      <form method="POST" action="{{ url_for('user.register') }}">

        <div class="form-group">
          <label for="exampleInputEmail1">用户名</label>
          <input type="text" class="form-control"  name="username">
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">邮箱</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
          <small id="emailHelp" class="form-text text-muted">我们永远不会与其他人分享您的电子邮件。</small>
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">验证码</label>
          <div class="input-group">
            <input type="text" class="form-control" name="captcha">
            <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label for="exampleInputPassword1">密码</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>

        <div class="form-group">
          <label for="exampleInputPassword1">确认密码</label>
          <input type="password" class="form-control"  name="password_confirm">
        </div>

        <button type="submit" class="btn btn-primary btn-block ">立即注册</button>

      </form>
    </div>
    <div class="col-sm"></div>
  </div>


{% endblock %}